name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"      
  workflow_dispatch:       

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate light mode snake
        uses: Platane/snk@v3
        with:
          github_user_name: tranhoangduy2006
          outputs: dist/snake.svg

      - name: Generate dark mode snake
        uses: Platane/snk@v3
        with:
          github_user_name: tranhoangduy2006
          outputs: dist/snake-dark.svg?palette=github-dark

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
